In [ ]:
import cx_Oracle
import pandas as pd

conn = cx_Oracle.connect("team/1234@192.168.0.52:32764/xe")

df = pd.read_sql('select article_id from article_article group by article_id', conn)

In [38]:
df.columns = ['article_id']
df['check'] = 1

In [39]:
df.head()

           article_id  check
0  101_001_0011308128      1
1  101_001_0011308200      1
2  101_001_0011308276      1
3  101_001_0011308308      1
4  101_001_0011308309      1

In [ ]:
file_name = 'total_article_ver1_20200427'
df2 = pd.read_csv('C:\\Users\\admin\\Documents\\RealTitle\\RealTitle\\data\\' + file_name + '.csv')

In [7]:
df2.head()

,article_id,article_url,article_category,article_media,article_date,article_title,article_content
0,105_014_0004366143,https://news.naver.com/main/read.nhn?mode=LSD&...,IT과학,파이낸셜뉴스,20200201,NBP 네이버 클로바 OCR기술 파트너 모집,문자인식기술 OCR 파트너사 모집 네이버 클라우드 플랫폼 AI사업 본격화 파이낸셜뉴...
1,105_014_0004366140,https://news.naver.com/main/read.nhn?mode=LSD&...,IT과학,파이낸셜뉴스,20200201,KISA 보안공지 사칭한 스미싱 문자 주의,출처 불분명한 문자 내 URL 인터넷주소 클릭 주의 한국인터넷진흥원 KISA 보안공...
2,105_293_0000026457,https://news.naver.com/main/read.nhn?mode=LSD&...,IT과학,블로터,20200201,파괴적 혁신은 기술과는 상관이 없다,파괴적 혁신은 기술이 아니라 기존 기업들의 고객가치사슬 CVC 중 일부를 끊어낼 수...
3,105_015_0004282535,https://news.naver.com/main/read.nhn?mode=LSD&...,IT과학,한국경제,20200201,94만 구독자 보유 유튜버 온도 디자인 표절 의혹에 결국 사과,직접 제작·판매한 제품 표절 의혹 당초 표절 부인하다 결국 판매 중단 유튜버 온도 ...
4,105_011_0003688312,https://news.naver.com/main/read.nhn?mode=LSD&...,IT과학,서울경제,20200201,일본서 감염 중국인 환자 2주간 국내 활동,日 환자 접촉 중국인 입국부터 확진까지 13일 걸려 “일본 중국인 환자 접촉자 중국...

In [40]:
df_merge = pd.merge(df, df2, how='outer')

In [50]:
df_merge.tail()

,article_id,check,article_url,article_category,article_media,article_date,article_title,article_content
1935149,100_056_0010824537,NaN,https://news.naver.com/main/read.nhn?mode=LSD&...,정치,KBS,20200424,민주당 ‘성추행’ 오거돈 시장 제명 절차 착수,민주당은 성추행 사건으로 사퇴한 오거돈 부산시장에 대한 징계 절차에 착수했습니다. ...
1935150,100_025_0002995552,NaN,https://news.naver.com/main/read.nhn?mode=LSD&...,정치,중앙일보,20200424,사진 오거돈 “여성 공무원에게 불필요한 신체 접촉”,총선 전 성추행 총선 뒤 사퇴 오거돈 ’여성 공무원에게 불필요한 신체 접촉“ 오거돈...
1935151,100_003_0009832030,NaN,https://news.naver.com/main/read.nhn?mode=LSD&...,정치,뉴시스,20200424,北·러시아 김정은 방러 1주년 맞아 협력 강화키로,서울 뉴시스 북한 주재 러시아대사관은 23일 페이스북 공식 계정에 올린 게시물에서 ...
1935152,100_025_0002995549,NaN,https://news.naver.com/main/read.nhn?mode=LSD&...,정치,중앙일보,20200424,사진 문 대통령 세계 최대 컨테이너선 명명식 참석,문 대통령 세계 최대 컨테이너선 명명식 참석 문재인 대통령과 부인 김정숙 여사가 2...
1935153,100_087_0000796430,NaN,https://news.naver.com/main/read.nhn?mode=LSD&...,정치,강원일보,20200424,“방사광가속기 유치…중부권 최대 과학산단 도약”,“방사광가속기 유치…중부권 최대 과학산단 도약” ◇2020 강원 미래 과학 포럼이 ...

In [57]:
import numpy as np
df_result = df_merge[df_merge['check'].isna() ]

In [59]:
df_result.head()

,article_id,check,article_url,article_category,article_media,article_date,article_title,article_content
588149,102_079_0003057418,NaN,https://news.naver.com/main/read.nhn?mode=LSD&...,사회,노컷뉴스,20180119,환경부·수도권 미세먼지 저감조치 발령요건 강화하자,CBS노컷뉴스 김민재 기자 환경부와 서울시·인천시·경기도가 수도권 미세먼지 비상저감...
588150,102_421_0003158886,NaN,https://news.naver.com/main/read.nhn?mode=LSD&...,사회,뉴스1,20180119,전남지역 예산담당 공무원들 18∼19일 고흥서 워크숍,전남 예산담당 공무원 워크숍. 고흥군 제공 뉴스1 © News1 지정운 기자 재정 ...
588151,102_001_0009824245,NaN,https://news.naver.com/main/read.nhn?mode=LSD&...,사회,연합뉴스,20180119,개회사 하는 김은경 환경부 장관,서울 연합뉴스 김은경 환경부 장관이 19일 오후 서울 서초구 엘타워에서 열린 통합물...
588152,102_001_0009824244,NaN,https://news.naver.com/main/read.nhn?mode=LSD&...,사회,연합뉴스,20180119,개회사 하는 김은경 환경부 장관,서울 연합뉴스 김은경 환경부 장관이 19일 오후 서울 서초구 엘타워에서 열린 통합물...
588153,102_001_0009824243,NaN,https://news.naver.com/main/read.nhn?mode=LSD&...,사회,연합뉴스,20180119,평화통일 기원합니다,고성 연합뉴스 이종건 기자 19일 고성 통일전망대를 찾은 관광객들이 평창동계올림픽 ...

In [60]:
df_result.shape

(1347005, 8)

In [61]:
df_result.columns

Index(['article_id', 'check', 'article_url', 'article_category',
       'article_media', 'article_date', 'article_title', 'article_content'],
      dtype='object')

In [64]:
df_result.drop('check', axis=1, inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [65]:
df_result.head()

,article_id,article_url,article_category,article_media,article_date,article_title,article_content
588149,102_079_0003057418,https://news.naver.com/main/read.nhn?mode=LSD&...,사회,노컷뉴스,20180119,환경부·수도권 미세먼지 저감조치 발령요건 강화하자,CBS노컷뉴스 김민재 기자 환경부와 서울시·인천시·경기도가 수도권 미세먼지 비상저감...
588150,102_421_0003158886,https://news.naver.com/main/read.nhn?mode=LSD&...,사회,뉴스1,20180119,전남지역 예산담당 공무원들 18∼19일 고흥서 워크숍,전남 예산담당 공무원 워크숍. 고흥군 제공 뉴스1 © News1 지정운 기자 재정 ...
588151,102_001_0009824245,https://news.naver.com/main/read.nhn?mode=LSD&...,사회,연합뉴스,20180119,개회사 하는 김은경 환경부 장관,서울 연합뉴스 김은경 환경부 장관이 19일 오후 서울 서초구 엘타워에서 열린 통합물...
588152,102_001_0009824244,https://news.naver.com/main/read.nhn?mode=LSD&...,사회,연합뉴스,20180119,개회사 하는 김은경 환경부 장관,서울 연합뉴스 김은경 환경부 장관이 19일 오후 서울 서초구 엘타워에서 열린 통합물...
588153,102_001_0009824243,https://news.naver.com/main/read.nhn?mode=LSD&...,사회,연합뉴스,20180119,평화통일 기원합니다,고성 연합뉴스 이종건 기자 19일 고성 통일전망대를 찾은 관광객들이 평창동계올림픽 ...

In [66]:
df_result.shape

(1347005, 7)